### ISSUE TITLE
Keep .modal-open on body

### ISSUE THREAD

**Issue by mouse0270** [danielpox/better-bootstrap-modals#2]
I am to lazy to do a pull request at the moment, so here is an update. If you add this code you will be able to keep the `.modal-open` class when people close one of the modals.
``` javascript
	$(".modal").on("hidden.bs.modal", function() {
		if (bbm_modals.length >= 1) {
			$('body').addClass('modal-open');
		}
	});
```

**Comment by danielpox** [comment]
This will be fixed in the next release (v0.4.0).
