### ISSUE TITLE
What is the point of bbm_modals?

### ISSUE THREAD

**Issue by mouse0270** [danielpox/better-bootstrap-modals#4]
Okay, so this is just me being curious, what is the point of the `bbm_modals` variable. It looks like it is used to store the modals, but there ins't any logical reason for doing this that I can understand. So I am just curious why you are doing it?

**Comment by danielpox** [comment]
Well, basically I have it there for future-proof applications, for example if in the future there would be a way to move around the modals or reorder them. I simply store them in an array for simplicity. Of course it is not necessary for the core function.
